os: linux
sudo: required
dist: trusty

language:
  - c

compiler:
  - gcc
  - clang

branches:
  only:
    - devel-cli

cache:
  directories:
    - libssh-0.7.3

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash .travis-install-libs.sh; fi

script:
  - mkdir build-cli && cd build-cli && cmake ../cli && make -j2

