language: c

sudo: required

services:
  - docker

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc

branches:
  only:
    - master
    - devel-server

cache:
  directories:
    - libssh-0.8.5
    - protobuf
    - protobuf-c
    - cmocka-1.1.1

before_install:
  - eval "${MATRIX_EVAL}"
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then bash .travis-install-libs.sh; fi

script:
  - mkdir build-cli && cd build-cli && cmake ../cli && make -j2
  - mkdir ../build-server && cd ../build-server && cmake ../server && make -j2 && ctest --output-on-failure && make integration-test
  - cd ..

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CC" = "gcc" ]; then codecov; fi
