os: linux
sudo: required
dist: trusty

language:
  - c

compiler:
  - gcc
  - clang

branches:
  only:
    - devel-server

cache:
  directories:
    - cmocka-1.0.1
    - libssh-0.7.3
    - protobuf
    - protobuf-c

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then bash .travis-install-libs.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CC" = "gcc" ]; then pip install --user codecov; export CFLAGS="-coverage"; fi

script:
  - mkdir build-server && cd build-server && cmake ../server && make -j2 && ctest -V

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CC" = "gcc" ]; then codecov; fi

