os: linux
sudo: required
dist: trusty

language:
  - c

compiler:
  - gcc
  - clang

branches:
  only:
    - master

cache:
  directories:
    - cmocka-1.0.1
    - libssh-0.7.3
    - protobuf
    - protobuf-c

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash .travis-install-libs.sh; fi

script:
  - mkdir build-cli && cd build-cli && cmake ../cli && make -j2
  - mkdir ../build-server && cd ../build-server && cmake ../server && make -j2 && sudo ctest -V
  - cd ..

after_success:
  - if [ "${CC}" = "gcc" ]; then bash <(curl -s https://codecov.io/bash); fi

